//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramSubjectService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProgramSubjectService.IProgramSubject")]
    public interface IProgramSubject
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramSubject/Add", ReplyAction="http://tempuri.org/IProgramSubject/AddResponse")]
        System.Threading.Tasks.Task AddAsync(University.BackEnd.Entities.ProgramSubject element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramSubject/Delete", ReplyAction="http://tempuri.org/IProgramSubject/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(University.BackEnd.Entities.ProgramSubject element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramSubject/Update", ReplyAction="http://tempuri.org/IProgramSubject/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(University.BackEnd.Entities.ProgramSubject element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramSubject/Get", ReplyAction="http://tempuri.org/IProgramSubject/GetResponse")]
        System.Threading.Tasks.Task<University.BackEnd.Entities.ProgramSubject> GetAsync(System.Guid identifer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramSubject/GetList", ReplyAction="http://tempuri.org/IProgramSubject/GetListResponse")]
        System.Threading.Tasks.Task<University.BackEnd.Entities.ProgramSubject[]> GetListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IProgramSubjectChannel : ProgramSubjectService.IProgramSubject, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ProgramSubjectClient : System.ServiceModel.ClientBase<ProgramSubjectService.IProgramSubject>, ProgramSubjectService.IProgramSubject
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProgramSubjectClient() : 
                base(ProgramSubjectClient.GetDefaultBinding(), ProgramSubjectClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ProgramSubjectEndPoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgramSubjectClient(EndpointConfiguration endpointConfiguration) : 
                base(ProgramSubjectClient.GetBindingForEndpoint(endpointConfiguration), ProgramSubjectClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgramSubjectClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProgramSubjectClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgramSubjectClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProgramSubjectClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgramSubjectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task AddAsync(University.BackEnd.Entities.ProgramSubject element)
        {
            return base.Channel.AddAsync(element);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(University.BackEnd.Entities.ProgramSubject element)
        {
            return base.Channel.DeleteAsync(element);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(University.BackEnd.Entities.ProgramSubject element)
        {
            return base.Channel.UpdateAsync(element);
        }
        
        public System.Threading.Tasks.Task<University.BackEnd.Entities.ProgramSubject> GetAsync(System.Guid identifer)
        {
            return base.Channel.GetAsync(identifer);
        }
        
        public System.Threading.Tasks.Task<University.BackEnd.Entities.ProgramSubject[]> GetListAsync()
        {
            return base.Channel.GetListAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProgramSubjectEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProgramSubjectEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://web-app-university-backend.azurewebsites.net/ProgramSubject.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProgramSubjectClient.GetBindingForEndpoint(EndpointConfiguration.ProgramSubjectEndPoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProgramSubjectClient.GetEndpointAddress(EndpointConfiguration.ProgramSubjectEndPoint);
        }
        
        public enum EndpointConfiguration
        {
            
            ProgramSubjectEndPoint,
        }
    }
}
