//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoomService.IRoom")]
    public interface IRoom
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoom/Add", ReplyAction="http://tempuri.org/IRoom/AddResponse")]
        System.Threading.Tasks.Task AddAsync(University.BackEnd.Entities.Room element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoom/Delete", ReplyAction="http://tempuri.org/IRoom/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(University.BackEnd.Entities.Room element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoom/Update", ReplyAction="http://tempuri.org/IRoom/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(University.BackEnd.Entities.Room element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoom/Get", ReplyAction="http://tempuri.org/IRoom/GetResponse")]
        System.Threading.Tasks.Task<University.BackEnd.Entities.Room> GetAsync(System.Guid identifer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoom/GetList", ReplyAction="http://tempuri.org/IRoom/GetListResponse")]
        System.Threading.Tasks.Task<University.BackEnd.Entities.Room[]> GetListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IRoomChannel : RoomService.IRoom, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class RoomClient : System.ServiceModel.ClientBase<RoomService.IRoom>, RoomService.IRoom
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RoomClient() : 
                base(RoomClient.GetDefaultBinding(), RoomClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.RoomEndPoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoomClient(EndpointConfiguration endpointConfiguration) : 
                base(RoomClient.GetBindingForEndpoint(endpointConfiguration), RoomClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoomClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RoomClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoomClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RoomClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoomClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task AddAsync(University.BackEnd.Entities.Room element)
        {
            return base.Channel.AddAsync(element);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(University.BackEnd.Entities.Room element)
        {
            return base.Channel.DeleteAsync(element);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(University.BackEnd.Entities.Room element)
        {
            return base.Channel.UpdateAsync(element);
        }
        
        public System.Threading.Tasks.Task<University.BackEnd.Entities.Room> GetAsync(System.Guid identifer)
        {
            return base.Channel.GetAsync(identifer);
        }
        
        public System.Threading.Tasks.Task<University.BackEnd.Entities.Room[]> GetListAsync()
        {
            return base.Channel.GetListAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RoomEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RoomEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://web-app-university-backend.azurewebsites.net/Room.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RoomClient.GetBindingForEndpoint(EndpointConfiguration.RoomEndPoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RoomClient.GetEndpointAddress(EndpointConfiguration.RoomEndPoint);
        }
        
        public enum EndpointConfiguration
        {
            
            RoomEndPoint,
        }
    }
}
