//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramSubjectPersonService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProgramSubjectPersonService.IProgramSubjectPerson")]
    public interface IProgramSubjectPerson
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramSubjectPerson/Add", ReplyAction="http://tempuri.org/IProgramSubjectPerson/AddResponse")]
        System.Threading.Tasks.Task AddAsync(University.BackEnd.Entities.ProgramSubjectPerson element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramSubjectPerson/Delete", ReplyAction="http://tempuri.org/IProgramSubjectPerson/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(University.BackEnd.Entities.ProgramSubjectPerson element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramSubjectPerson/Update", ReplyAction="http://tempuri.org/IProgramSubjectPerson/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(University.BackEnd.Entities.ProgramSubjectPerson element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramSubjectPerson/Get", ReplyAction="http://tempuri.org/IProgramSubjectPerson/GetResponse")]
        System.Threading.Tasks.Task<University.BackEnd.Entities.ProgramSubjectPerson> GetAsync(System.Guid identifer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgramSubjectPerson/GetList", ReplyAction="http://tempuri.org/IProgramSubjectPerson/GetListResponse")]
        System.Threading.Tasks.Task<University.BackEnd.Entities.ProgramSubjectPerson[]> GetListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IProgramSubjectPersonChannel : ProgramSubjectPersonService.IProgramSubjectPerson, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ProgramSubjectPersonClient : System.ServiceModel.ClientBase<ProgramSubjectPersonService.IProgramSubjectPerson>, ProgramSubjectPersonService.IProgramSubjectPerson
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProgramSubjectPersonClient() : 
                base(ProgramSubjectPersonClient.GetDefaultBinding(), ProgramSubjectPersonClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ProgramSubjectPersonEndPoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgramSubjectPersonClient(EndpointConfiguration endpointConfiguration) : 
                base(ProgramSubjectPersonClient.GetBindingForEndpoint(endpointConfiguration), ProgramSubjectPersonClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgramSubjectPersonClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProgramSubjectPersonClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgramSubjectPersonClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProgramSubjectPersonClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgramSubjectPersonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task AddAsync(University.BackEnd.Entities.ProgramSubjectPerson element)
        {
            return base.Channel.AddAsync(element);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(University.BackEnd.Entities.ProgramSubjectPerson element)
        {
            return base.Channel.DeleteAsync(element);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(University.BackEnd.Entities.ProgramSubjectPerson element)
        {
            return base.Channel.UpdateAsync(element);
        }
        
        public System.Threading.Tasks.Task<University.BackEnd.Entities.ProgramSubjectPerson> GetAsync(System.Guid identifer)
        {
            return base.Channel.GetAsync(identifer);
        }
        
        public System.Threading.Tasks.Task<University.BackEnd.Entities.ProgramSubjectPerson[]> GetListAsync()
        {
            return base.Channel.GetListAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProgramSubjectPersonEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProgramSubjectPersonEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://web-app-university-backend.azurewebsites.net/ProgramSubjectPerson.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProgramSubjectPersonClient.GetBindingForEndpoint(EndpointConfiguration.ProgramSubjectPersonEndPoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProgramSubjectPersonClient.GetEndpointAddress(EndpointConfiguration.ProgramSubjectPersonEndPoint);
        }
        
        public enum EndpointConfiguration
        {
            
            ProgramSubjectPersonEndPoint,
        }
    }
}
