//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubjectService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SubjectService.ISubject")]
    public interface ISubject
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubject/Add", ReplyAction="http://tempuri.org/ISubject/AddResponse")]
        System.Threading.Tasks.Task AddAsync(University.BackEnd.Entities.Subject element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubject/Delete", ReplyAction="http://tempuri.org/ISubject/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(University.BackEnd.Entities.Subject element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubject/Update", ReplyAction="http://tempuri.org/ISubject/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(University.BackEnd.Entities.Subject element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubject/Get", ReplyAction="http://tempuri.org/ISubject/GetResponse")]
        System.Threading.Tasks.Task<University.BackEnd.Entities.Subject> GetAsync(System.Guid identifer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubject/GetList", ReplyAction="http://tempuri.org/ISubject/GetListResponse")]
        System.Threading.Tasks.Task<University.BackEnd.Entities.Subject[]> GetListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ISubjectChannel : SubjectService.ISubject, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SubjectClient : System.ServiceModel.ClientBase<SubjectService.ISubject>, SubjectService.ISubject
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SubjectClient() : 
                base(SubjectClient.GetDefaultBinding(), SubjectClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SubjectEndPoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubjectClient(EndpointConfiguration endpointConfiguration) : 
                base(SubjectClient.GetBindingForEndpoint(endpointConfiguration), SubjectClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubjectClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SubjectClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubjectClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SubjectClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubjectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task AddAsync(University.BackEnd.Entities.Subject element)
        {
            return base.Channel.AddAsync(element);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(University.BackEnd.Entities.Subject element)
        {
            return base.Channel.DeleteAsync(element);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(University.BackEnd.Entities.Subject element)
        {
            return base.Channel.UpdateAsync(element);
        }
        
        public System.Threading.Tasks.Task<University.BackEnd.Entities.Subject> GetAsync(System.Guid identifer)
        {
            return base.Channel.GetAsync(identifer);
        }
        
        public System.Threading.Tasks.Task<University.BackEnd.Entities.Subject[]> GetListAsync()
        {
            return base.Channel.GetListAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SubjectEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SubjectEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://web-app-university-backend.azurewebsites.net/Subject.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SubjectClient.GetBindingForEndpoint(EndpointConfiguration.SubjectEndPoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SubjectClient.GetEndpointAddress(EndpointConfiguration.SubjectEndPoint);
        }
        
        public enum EndpointConfiguration
        {
            
            SubjectEndPoint,
        }
    }
}
