//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomSubjectService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoomSubjectService.IRoomSubject")]
    public interface IRoomSubject
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomSubject/Add", ReplyAction="http://tempuri.org/IRoomSubject/AddResponse")]
        System.Threading.Tasks.Task AddAsync(University.BackEnd.Entities.RoomSubject element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomSubject/Delete", ReplyAction="http://tempuri.org/IRoomSubject/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(University.BackEnd.Entities.RoomSubject element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomSubject/Update", ReplyAction="http://tempuri.org/IRoomSubject/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(University.BackEnd.Entities.RoomSubject element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomSubject/Get", ReplyAction="http://tempuri.org/IRoomSubject/GetResponse")]
        System.Threading.Tasks.Task<University.BackEnd.Entities.RoomSubject> GetAsync(System.Guid identifer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoomSubject/GetList", ReplyAction="http://tempuri.org/IRoomSubject/GetListResponse")]
        System.Threading.Tasks.Task<University.BackEnd.Entities.RoomSubject[]> GetListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IRoomSubjectChannel : RoomSubjectService.IRoomSubject, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class RoomSubjectClient : System.ServiceModel.ClientBase<RoomSubjectService.IRoomSubject>, RoomSubjectService.IRoomSubject
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RoomSubjectClient() : 
                base(RoomSubjectClient.GetDefaultBinding(), RoomSubjectClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.RoomSubjectEndPoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoomSubjectClient(EndpointConfiguration endpointConfiguration) : 
                base(RoomSubjectClient.GetBindingForEndpoint(endpointConfiguration), RoomSubjectClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoomSubjectClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RoomSubjectClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoomSubjectClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RoomSubjectClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RoomSubjectClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task AddAsync(University.BackEnd.Entities.RoomSubject element)
        {
            return base.Channel.AddAsync(element);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(University.BackEnd.Entities.RoomSubject element)
        {
            return base.Channel.DeleteAsync(element);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(University.BackEnd.Entities.RoomSubject element)
        {
            return base.Channel.UpdateAsync(element);
        }
        
        public System.Threading.Tasks.Task<University.BackEnd.Entities.RoomSubject> GetAsync(System.Guid identifer)
        {
            return base.Channel.GetAsync(identifer);
        }
        
        public System.Threading.Tasks.Task<University.BackEnd.Entities.RoomSubject[]> GetListAsync()
        {
            return base.Channel.GetListAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RoomSubjectEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.RoomSubjectEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://web-app-university-backend.azurewebsites.net/RoomSubject.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RoomSubjectClient.GetBindingForEndpoint(EndpointConfiguration.RoomSubjectEndPoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RoomSubjectClient.GetEndpointAddress(EndpointConfiguration.RoomSubjectEndPoint);
        }
        
        public enum EndpointConfiguration
        {
            
            RoomSubjectEndPoint,
        }
    }
}
