//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProgramService.IProgram")]
    public interface IProgram
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgram/Add", ReplyAction="http://tempuri.org/IProgram/AddResponse")]
        System.Threading.Tasks.Task AddAsync(University.BackEnd.Entities.Program element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgram/Delete", ReplyAction="http://tempuri.org/IProgram/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(University.BackEnd.Entities.Program element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgram/Update", ReplyAction="http://tempuri.org/IProgram/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(University.BackEnd.Entities.Program element);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgram/Get", ReplyAction="http://tempuri.org/IProgram/GetResponse")]
        System.Threading.Tasks.Task<University.BackEnd.Entities.Program> GetAsync(System.Guid identifer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProgram/GetList", ReplyAction="http://tempuri.org/IProgram/GetListResponse")]
        System.Threading.Tasks.Task<University.BackEnd.Entities.Program[]> GetListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IProgramChannel : ProgramService.IProgram, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ProgramClient : System.ServiceModel.ClientBase<ProgramService.IProgram>, ProgramService.IProgram
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProgramClient() : 
                base(ProgramClient.GetDefaultBinding(), ProgramClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ProgramEndPoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgramClient(EndpointConfiguration endpointConfiguration) : 
                base(ProgramClient.GetBindingForEndpoint(endpointConfiguration), ProgramClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgramClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProgramClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgramClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProgramClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProgramClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task AddAsync(University.BackEnd.Entities.Program element)
        {
            return base.Channel.AddAsync(element);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(University.BackEnd.Entities.Program element)
        {
            return base.Channel.DeleteAsync(element);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(University.BackEnd.Entities.Program element)
        {
            return base.Channel.UpdateAsync(element);
        }
        
        public System.Threading.Tasks.Task<University.BackEnd.Entities.Program> GetAsync(System.Guid identifer)
        {
            return base.Channel.GetAsync(identifer);
        }
        
        public System.Threading.Tasks.Task<University.BackEnd.Entities.Program[]> GetListAsync()
        {
            return base.Channel.GetListAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProgramEndPoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProgramEndPoint))
            {
                return new System.ServiceModel.EndpointAddress("http://web-app-university-backend.azurewebsites.net/Program.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProgramClient.GetBindingForEndpoint(EndpointConfiguration.ProgramEndPoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProgramClient.GetEndpointAddress(EndpointConfiguration.ProgramEndPoint);
        }
        
        public enum EndpointConfiguration
        {
            
            ProgramEndPoint,
        }
    }
}
